<?php
/**
 * @package     Joomla.Site
 * @subpackage  mod_guideman_nav
 *
 * @copyright   Copyright (C) 2005 - 2016 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
 defined('_JEXEC') or die('Restricted access');

// - - - - - - - - - - - - - - - - - -
// Check Language
// - - - - - - - - - - - - - - - - - -
	$lang = JFactory::getLanguage();
	$lang_tag = $lang->getTag();
  $no_user = false;
  // - - - - - - - - - - - - - - - - - -
  // Get User Information
  // - - - - - - - - - - - - - - - - - -
  if (JFactory::getUser()->id) {
    $db = JFactory::getDbo();
  	$query = $db->getQuery(true);
  	$query->select('*');
  	$query->from($db->quoteName('#__guideman_contacts'));
  	$query->where($db->quoteName('user_id')." = ".JFactory::getUser()->id);
  	$db->setQuery($query);
  	$contactarray = $db->loadAssoc();
    //echo "taal: "; var_dump($lang_tag);
  	switch ($lang_tag) {
  		case "en-GB":
  			$routelang = "";
  			$routeshort = "";
  			$routelangend = "";
  			break;
  		case "fr-FR":
  			$routelang = "fr/";
  			$routeshort = "-fr";
  			$routelangend = "-fr";
  			break;
  		case "nl-NL":
  			$routelang = "nl/";
  			$routeshort = "-nl";
  			$routelangend = "-nl";
  			break;
  		case "pt-BR":
  			$routelang = "pt/";
  			$routeshort = "-pt";
  			$routelangend = "-pt";
  			break;
      case "es-ES":
  			$routelang = "es/";
  			$routeshort = "-es";
  			$routelangend = "-es";
  		  break;
      default:
  			$routelang = "";
  			$routeshort = "";
  			$routelangend = "";
  			break;
  	}
    // - - - - - - - - - - - - - - - - - -
    // Check User Access Groupe
    // - - - - - - - - - - - - - - - - - -
  	$user = JFactory::getUser();
  	$groups = JUserHelper::getUserGroups($user->get('id'));
  	// UserGroups
  	// 0 = Guides Premium
  	// 1 = Travel Agencies
  	// 2 = Transportation
  	// $UserGroup = 0;
  	$fullaccess = FALSE;
  	if (in_array('10',$groups)) {
  		$fullaccess = TRUE;
  		};
  	if (in_array('13',$groups)) {
  		$fullaccess = TRUE;
  		};
  	if ((in_array('11',$groups)) OR (in_array('12',$groups))) {
  		$routeshort .= '-ta';
  		$fullaccess = TRUE;
  		};
  	if ((in_array('14',$groups)) OR (in_array('15',$groups))) {
  		$routeshort .= '-tr';
  		$fullaccess = TRUE;
  		};
  } else {
    $no_user = true;
  }

?>
<script type="text/javascript">
<!--

/*
 *	Dynamically Tabbed Welcome Table v2
 *	Generated by the DTT Generator
 *	Created By Jordan a.k.a. Triad
 *	http://support.proboards.com
 */

var DTT = {

	selected:
	{
		id: "directories",
		listItem: {}
	},

	$: function(id)
	{
		if(id)
			return document.getElementById(id);
		return false;
	},

	init: function()
	{
		var tCookie = this.getCookie();

		if(tCookie.tab)
		{
			this.toggleTab(tCookie.tab);
		}

		if(tCookie.show == "0")
		{
			this.$("pro_collapse").style.display = "none";
		}
	},

	setCookie: function(tab, show)
	{
		var tTab = "";
		var tShow = "";
		var tCookie = this.getCookie();

		if(tab)
			tTab = tab;
		else
			tTab = (tCookie.tab) ? tCookie.tab : this.selected.id;

		if(show)
			tShow = show;
		else
			tShow = (tCookie.show) ? tCookie.show : "1";

		document.cookie = "DTTData=tab=" + encodeURI(tTab) + "|show=" + encodeURI(tShow) + ";expires=Sat, 20 Jan 3000 12:12:12 UTC; path=/;";
	},

	getCookie: function()
	{
		if(document.cookie.match(new RegExp("DTTData=(.+?)($|;)","gi")))
		{
			var data = decodeURI(RegExp.$1);

			return {
				tab: data.split("=")[1].split("|")[0],
				show: data.split("=")[2]
			};
		}

		return false;
	},

	toggleTab: function(id)
	{
		var newID = id.substr(4);

		if(this.selected.id != newID && this.$(id))
		{
			if(this.$("nav_" + this.selected.id))
			{
				this.$("nav_" + this.selected.id).className = "tabbg";
				this.$("pro_" + this.selected.id).style.display = "none";
			}

			this.selected.id = newID;
			this.$("nav_" + this.selected.id).className = "tabbgselected";
			this.$("pro_" + this.selected.id).style.display = "";

			this.setCookie(id, false);
		}
	},

	toggleTable: function()
	{
		if(this.$("pro_collapse").style.display == "")
		{
			this.$("pro_collapse").style.display = "none";
			this.setCookie(false, "0");
		}
		else
		{
			this.$("pro_collapse").style.display = "";
			this.setCookie(false, "1");
		}
	},

	toggleListItem: function(id, name)
	{
		if(this.selected.listItem[id])
		{
			if(this.selected.listItem[id].name == name)
			{
				if(this.selected.listItem[id].object.style.display == "")
				{
					this.selected.listItem[id].object.style.display = "none";
					this.$("pro_" + id + "_default").style.display = "";
				}
				else
				{
					this.$("pro_" + id + "_default").style.display = "none";
					this.selected.listItem[id].object.style.display = "";
				}
				return true;
			}
			else
				this.selected.listItem[id].object.style.display = "none";
		}

		this.selected.listItem[id] = {
			name: name,
			object: this.$("pro_" + id + "_" + name)
		};

		this.$("pro_" + id + "_default").style.display = "none";
		this.selected.listItem[id].object.style.display = "";
	}
};

//-->
</script>

<style type="text/css">
<!--
.gm_nav_form{
	background-color: #000000;
}

.tabbg {
	background-color: #000000;
	color: #ffd600;
	border-bottom: 1px solid #000000;
  padding: 5px 5px 5px 5px;
}

.tabbgselected {
	background-color: #00ad52;
	color: #000000;
  border-top: 1px solid #000000;
  border-right: 1px solid #000000;
	border-bottom: 2px solid #ffd600;
  border-left: 1px solid #000000;
  border-top-left-radius: 10px;
  border-top-right-radius: 10px;
  padding: 5px 5px 8px 5px;
}

.tabside {
	background-color: #00ad52;
	color: #000000;
  border-top: 1px solid;
  border-right: 1px solid;
	border-bottom: 1px solid;
  border-left: 1px solid;
  border-radius: 10px;
  padding: 5px 5px 8px 5px;
}
.img-circular{
  margin-top: 15px;
  width: 75px;
  height: 75px;
  background-image: url('<?php echo JUri::root(true); ?>/images/guideman/contacts/<?php echo $contactarray['image'] ?>');
  background-size: cover;
  display: block;
  border-radius: 35px;
  -webkit-border-radius: 35px;
  -moz-border-radius: 35px;
}

#pro_tabs td, #pro_sidebar td {
	font-size: 10pt;
	font-weight: bold;
	text-align: center;
}

#pro_tabs td {
	width: 20%;
	cursor: pointer;
}

#pro_content {
	font-size: 10pt;
	text-align: left;
	padding: 10px;
}

#pro_threads {
	font-size: 10pt;
	font-weight: bold;
	line-height: 1.5em;
	text-align: left;
}

-->
</style>

<form id="mod_guideman_nav" action="<?php echo JRoute::_($route); ?>" method="get" class="gm_nav_form">
<?php
  if (!$no_user) { ?>
    <table width="100%" align="center" cellspacing="1" cellpadding="0" class="bordercolor">
  		<tr id="pro_collapse" style="display:;">
  			<td width="80%" align="center" class="windowbg" valign="top">
  				<table width="100%" cellspacing="0" cellpadding="5">
  					<tr id="pro_tabs">
  						<td class="tabbg" onclick="DTT.toggleTab(this.id);" id="nav_locators"><?php echo ' ' . JText::_('MOD_GM_LOCATORS'); ?></td>
  						<td class="tabbg" onclick="DTT.toggleTab(this.id);" id="nav_directories"><?php echo ' ' . JText::_('MOD_GM_DIRECTORIES'); ?></td>
  						<?php if ($fullaccess) : ?>
  							<td class="tabbg" onclick="DTT.toggleTab(this.id);" id="nav_serviceorders" style="border-right: none;"><?php echo ' ' . JText::_('MOD_GM_OS'); ?></td>
  							<td class="tabbg" onclick="DTT.toggleTab(this.id);" id="nav_settings" style="border-right: none;"><?php echo ' ' . JText::_('MOD_GM_SETTINGS'); ?></td>
  						<?php endif; ?>
  						<td class="tabbgselected" onclick="DTT.toggleTab(this.id);" id="nav_profile"><?php echo ' ' . JText::_('MOD_GM_PROFILE'); ?></td>
  					</tr>
  					<tr>
  						<td class="windowbg" id="pro_content" colspan="5">
  							<div id="pro_locators" style="display: none;">
  								<div class="well">
  									<div class="row-fluid">
  										<div class="span12">
  											<div class="row-fluid">
  												<div class="span4">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>tools<?php echo $routelangend ?>/locaters<?php echo $routelangend ?>/accomodations<?php echo $routelangend ?>"><em class="fa fa-bed fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_LOCATORS_HOTELS'); ?></h6>
  														</span>
  													</center>
  												</div>
  												<div class="span4">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>tools<?php echo $routelangend ?>/locaters<?php echo $routelangend ?>/restaurants<?php echo $routelangend ?>"><em class="fa fa-cutlery fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_LOCATORS_RESTAURANTS'); ?></h6>
  														</span>
  													</center>
  												</div>
  												<div class="span4">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>tools<?php echo $routelangend ?>/locaters<?php echo $routelangend ?>/attractions<?php echo $routelangend ?>"><em class="fa fa-map-pin fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_LOCATORS_ATTRACTIONS'); ?></h6>
  														</span>
  													</center>
  												</div>
  											</div>
  										</div>
  									</div>
  								</div>
  							</div>
  							<div id="pro_directories">
  								<div class="well">
  									<div class="row-fluid">
  										<div class="span12">
  											<div class="row-fluid">
  												<div class="span2">
  													<center>
  														<?php if (!$fullaccess) { ?>
  															<a href="index.php/<?php echo $routelang ?>tools<?php echo $routelangend ?>/directories<?php echo $routelangend ?>/guides<?php echo $routelangend ?>"><em class="fa fa-map-signs fa-2x fa-border"></em></a>
  															<span class="visible-desktop">
  																<h6><?php echo ' ' . JText::_('MOD_GM_DIRECTORIES_GUIDES'); ?></h6>
  															</span>
  														<?php }
  														else { ?>
  															<a href="index.php/<?php echo $routelang ?>tools<?php echo $routelangend ?>/directories<?php echo $routelangend ?>/guides<?php echo $routelangend ?>/search-guides-by-language<?php echo $routelangend ?>"><em class="fa fa-map-signs fa-2x fa-border"></em></a>
  															<span class="visible-desktop">
  																<h6><?php echo ' ' . JText::_('MOD_GM_DIRECTORIES_GUIDES'); ?></h6>
  															</span>
  															<?php } ?>
  													</center>
  												</div>
  												<div class="span2">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>tools<?php echo $routelangend ?>/directories<?php echo $routelangend ?>/travel-agencies<?php echo $routelangend ?>"><em class="fa fa-suitcase fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_DIRECTORIES_TRAVEL_AGENCIES'); ?></h6>
  														</span>
  													</center>
  												</div>
  												<div class="span2">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>tools<?php echo $routelangend ?>/directories<?php echo $routelangend ?>/hotels<?php echo $routelangend ?>"><em class="fa fa-bed fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_DIRECTORIES_HOTELS'); ?></h6>
  														</span>
  													</center>
  												</div>
  												<div class="span2">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>tools<?php echo $routelangend ?>/directories<?php echo $routelangend ?>/restaurants<?php echo $routelangend ?>"><em class="fa fa-cutlery fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_DIRECTORIES_RESTAURANTS'); ?></h6>
  														</span>
  													</center>
  												</div>
  												<div class="span2">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>tools<?php echo $routelangend ?>/directories<?php echo $routelangend ?>/attractions<?php echo $routelangend ?>"><em class="fa fa-map-pin fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_DIRECTORIES_ATTRACTIONS'); ?></h6>
  														</span>
  													</center>
  												</div>
  												<div class="span2">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>tools<?php echo $routelangend ?>/directories<?php echo $routelangend ?>/transportation<?php echo $routelangend ?>"><em class="fa fa-bus fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_DIRECTORIES_TRANSPORTATION'); ?></h6>
  														</span>
  													</center>
  												</div>
  											</div>
  										</div>
  									</div>
  								</div>
  							</div>
  							<div id="pro_serviceorders" style="display: none;">
  								<div class="well">
  									<div class="row-fluid">
  										<div class="span12">
  											<div class="row-fluid">
  												<div class="span6">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>manage<?php echo $routeshort ?>/service-orders<?php echo $routeshort ?>"><em class="fa fa-briefcase fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_SO_SERVICE_ORDERS'); ?></h6>
  														</span>
  													</center>
  												</div>
  												<div class="span6">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>manage<?php echo $routeshort ?>/service-orders<?php echo $routeshort ?>/service-orders-details<?php echo $routeshort ?>"><em class="fa fa-tasks fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_SO_ORDER_DETAILS'); ?></h6>
  														</span>
  													</center>
  												</div>
  											</div>
  										</div>
  									</div>
  								</div>
  							</div>

  							<div id="pro_settings" style="display: none;">
  								<div class="well">
  									<div class="row-fluid">
  										<div class="span12">
  											<div class="row-fluid">
  												<div class="span2">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>manage<?php echo $routeshort ?>/settings<?php echo $routeshort ?>/manage-services<?php echo $routeshort ?>"><em class="fa fa-list fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_SETTINGS_SERVICES'); ?></h6>
  														</span>
  													</center>
  												</div>
  												<div class="span2">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>manage<?php echo $routeshort ?>/settings<?php echo $routeshort ?>/manage-phone-labels<?php echo $routeshort ?>"><em class="fa fa-phone fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_SETTINGS_PHONE_LABELS'); ?></h6>
  														</span>
  													</center>
  												</div>
  												<div class="span2">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>manage<?php echo $routeshort ?>/settings<?php echo $routeshort ?>/manage-address-labels<?php echo $routeshort ?>"><em class="fa fa-home fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_SETTINGS_ADDRESS_LABELS'); ?></h6>
  														</span>
  													</center>
  												</div>
  												<div class="span2">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>manage<?php echo $routeshort ?>/settings<?php echo $routeshort ?>/manage-pricing<?php echo $routeshort ?>"><em class="fa fa-usd fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_SETTINGS_PRICING'); ?></h6>
  														</span>
  													</center>
  												</div>
  												<div class="span2">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>manage<?php echo $routeshort ?>/settings<?php echo $routeshort ?>/manage-remunerations<?php echo $routeshort ?>"><em class="fa fa-usd fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_SETTINGS_REMUNERATIONS'); ?></h6>
  														</span>
  													</center>
  												</div>
  												<div class="span2">
  													<center>
  														<a href="index.php/<?php echo $routelang ?>manage<?php echo $routeshort ?>/settings<?php echo $routeshort ?>/general-conditions<?php echo $routeshort ?>"><em class="fa fa-file-text-o fa-2x fa-border"></em></a>
  														<span class="visible-desktop">
  															<h6><?php echo ' ' . JText::_('MOD_GM_SETTINGS_GENERAL_CONDITIONS'); ?></h6>
  														</span>
  													</center>
  												</div>
  											</div>
  										</div>
  									</div>
  								</div>
  							</div>

  							<div id="pro_profile" style="display: none;">
  									<form id="mod-navigate_profile" action="<?php echo JRoute::_($route); ?>" method="get" class="form-search">
  										<body bgcolor="FFFFFF">
  											<div class="well">
  												<div class="row-fluid">
  													<div class="span12">
  														<div class="row-fluid">
  															<div class="span1">
  																<center>
  																	<a href="index.php/<?php echo $routelang ?>account<?php echo $routelangend ?>"><em class="fa fa-user fa-2x fa-border"></em></a>
  																	<span class="visible-desktop">
  																		<h6><?php echo ' ' . JText::_('MOD_GM_LIST_ACCOUNT'); ?></h6>
  																	</span>
  																</center>
  															</div>
  															<div class="span1">
  																<center>
  																	<a href="index.php/<?php echo $routelang ?>companies<?php echo $routelangend ?>"><em class="fa fa-building fa-2x fa-border"></em></a>
  																	<span class="visible-desktop">
  																		<h6><?php echo ' ' . JText::_('MOD_GM_LIST_PROFILE_COMPANIES'); ?></h6>
  																	</span>
  																</center>
  															</div>
  															<div class="span1">
  																<center>
  																	<span class="visible-desktop">
  																	<a href="index.php/<?php echo $routelang ?>addresses<?php echo $routelangend ?>"><em class="fa fa-home fa-2x fa-border"></em></a>
  																		<h6><?php echo ' ' . JText::_('MOD_GM_LIST_PROFILE_ADDRESSES'); ?></h6>
  																	</span>
  																</center>
  															</div>
  															<div class="span1">
  																<center>
  																	<a href="index.php/<?php echo $routelang ?>phones<?php echo $routelangend ?>"><em class="fa fa-phone fa-2x fa-border"></em></a>
  																	<span class="visible-desktop">
  																		<h6><?php echo ' ' . JText::_('MOD_GM_LIST_PROFILE_PHONES'); ?></h6>
  																	</span>
  																</center>
  															</div>
  															<div class="span1">
  																<center>
  																	<a href="index.php/<?php echo $routelang ?>documents<?php echo $routelangend ?>"><em class="fa fa-file-text-o fa-2x fa-border"></em></a>
  																	<span class="visible-desktop">
  																		<h6><?php echo ' ' . JText::_('MOD_GM_LIST_PROFILE_DOCUMENTS'); ?></h6>
  																	</span>
  																</center>
  															</div>
  															<div class="span1">
  																<center>
  																	<a href="index.php/<?php echo $routelang ?>languages<?php echo $routelangend ?>"><em class="fa fa-language fa-2x fa-border"></em></a>
  																	<span class="visible-desktop">
  																		<h6><?php echo ' ' . JText::_('MOD_GM_LIST_PROFILE_LANGUAGES'); ?></h6>
  																	</span>
  																</center>
  															</div>
  															<div class="span1">
  																<center>
  																	<a href="index.php/<?php echo $routelang ?>social<?php echo $routelangend ?>"><em class="fa fa-users fa-2x fa-border"></em></a>
  																	<span class="visible-desktop">
  																		<h6><?php echo ' ' . JText::_('MOD_GM_LIST_PROFILE_NETWORKING'); ?></h6>
  																	</span>
  																</center>
  															</div>
  															<div class="span1">
  																<center>
  																	<a href="index.php/<?php echo $routelang ?>vehicles<?php echo $routelangend ?>"><em class="fa fa-car fa-2x fa-border"></em></a>
  																	<span class="visible-desktop">
  																		<h6><?php echo ' ' . JText::_('MOD_GM_LIST_PROFILE_VEHICLES'); ?></h6>
  																	</span>
  																</center>
  															</div>
  															<div class="span1">
  																<center>
  																	<a href="index.php/<?php echo $routelang ?>bank-accounts<?php echo $routelangend ?>"><em class="fa fa-university fa-2x fa-border"></em></a>
  																	<span class="visible-desktop">
  																		<h6><?php echo ' ' . JText::_('MOD_GM_LIST_PROFILE_BANKSACCOUNTS'); ?></h6>
  																	</span>
  																</center>
  															</div>
  															<div class="span1">
  																<center>
  																	<a href="index.php/<?php echo $routelang ?>membership-information<?php echo $routelangend ?>"><em class="fa fa-shopping-cart fa-2x fa-border"></em></a>
  																	<span class="visible-desktop">
  																		<h6><?php echo ' ' . JText::_('MOD_GM_MEMBERSHIP_INFORMATION'); ?></h6>
  																	</span>
  																</center>
  															</div>
  														</div>
  													</div>
  												</div>
  											</div>
  										</body>
  									</form>
  							</div>
  						</td>
  					</tr>
  				</table>
  			</td>
  			<td width="20%" class="windowbg" valign="top">
  				<table width="100%" cellspacing="0" cellpadding="4">
  					<tr id="pro_sidebar">
  						<td align="center" class="tabside" style="border-right: none;">
  							<?php echo ' ' . JText::_('MOD_GM_INFORMATION'); ?>
  						</td>
  					</tr>
  					<tr>
  						<td class="windowbg" valign="top">
  							<div id="pro_threads">
  								<font color="white">
  									<div class="span12">
  										<div class="row-fluid">
  											<div class="span7">
  												<h3>
  													<?php
  														switch ($contactarray['catid']) {
  															case 24:
  																echo JText::_('MOD_GM_GUIDE');
  																break;
  															case 25:
  																echo JText::_('MOD_GM_TRAVEL_AGENCY');
  																break;
  															case 26:
  																echo JText::_('MOD_GM_TRANSPORTATION');
  																break;
  															case 27:
  																echo JText::_('MOD_GM_HOTEL');
  																break;
  															case 28:
  																echo JText::_('MOD_GM_RESTAURANT');
  																break;
  															case 30:
  																echo JText::_('MOD_GM_ATTRACTION');
  																break;
  															case 31:
  																echo JText::_('MOD_GM_TRAVELER');
  																break;
  															case 87:
  																echo JText::_('MOD_GM_OPERATOR');
  																break;
  															case 98:
  																echo JText::_('MOD_GM_OTHER_SERVICES');
  																break;
  															case 99:
  																echo JText::_('MOD_GM_TRAVELER');
  																break;
  															case 100:
  																echo JText::_('MOD_GM_DRIVER');
  																break;
  															default:
  																echo JText::_('MOD_GM_USER');
  																break;
  														}
  													?>
  												</h3>
  												<?php echo $contactarray['name'] ?><br>
  												<?php
  												if ($contactarray['con_position']) {
  													echo $contactarray['con_position'] . "</br>";
  												} ?>
  												<span class="badge badge-warning"><?php echo $contactarray['id'] ?></span><?php echo " ".$contactarray['alias'] ?>
  												</font>
  											</div>
  										<div class="row-fluid">
  											<div class="span5">
  												<center>
                            <div class="img-circular"></div>
  												</center>
  											</div>
  										</div>
  									</div>
  								</div>
  							</div>
  						</td>
  					</tr>
  				</table>
  			</td>
  		</tr>
  	</table>
  <?php } ?>
</form>

<script type="text/javascript">
<!--

DTT.init();

//-->
</script>
